[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science", "mathematics", "algorithms"]
description = "Multi-platform high-performance compute language extension for Rust."
edition.workspace = true
keywords = ["gpu", "cuda", "wgpu", "gpgpu", "tensor"]
license.workspace = true
name = "cubecl"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl"
rust-version = "1.80"
version.workspace = true

[features]
default = [
    "std",
    "linalg",
    "cubecl-core/default",
    "cubecl-cuda?/default",
    "cubecl-hip?/default",
    "cubecl-wgpu?/default",
]
exclusive-memory-only = ["cubecl-wgpu?/exclusive-memory-only"]
linalg = ["dep:cubecl-linalg"]
reduce = ["dep:cubecl-reduce"]
std = ["cubecl-core/std", "cubecl-wgpu?/std", "cubecl-cuda?/std"]
template = ["cubecl-core/template"]

# Runtimes
cuda = ["cubecl-cuda"]
hip = ["cubecl-hip"]
hip-intrinsic = ["hip", "cubecl-hip/wmma-intrinsics"]
wgpu = ["cubecl-wgpu"]
wgpu-spirv = ["wgpu", "cubecl-wgpu/spirv"]
mlir = ["cubecl-mlir"]

[dependencies]
cubecl-core = { path = "../cubecl-core", version = "0.5.0", default-features = false }
cubecl-cuda = { path = "../cubecl-cuda", version = "0.5.0", default-features = false, optional = true }
cubecl-hip = { path = "../cubecl-hip", version = "0.5.0", default-features = false, optional = true }
cubecl-linalg = { path = "../cubecl-linalg", version = "0.5.0", default-features = false, optional = true }
cubecl-reduce = { path = "../cubecl-reduce", version = "0.5.0", default-features = false, optional = true }
cubecl-runtime = { path = "../cubecl-runtime", version = "0.5.0", default-features = false }
cubecl-wgpu = { path = "../cubecl-wgpu", version = "0.5.0", default-features = false, optional = true }
cubecl-mlir = { path = "../cubecl-mlir", version = "0.5.0", default-features = false, optional = true }
half = { workspace = true }

[[bench]]
harness = false
name = "matmul"

[[bench]]
harness = false
name = "memcpy_async"

[[bench]]
harness = false
name = "unary"
