[package]
authors = [
    "nathanielsimard <nathaniel.simard.42@gmail.com>",
    "louisfd <louisfd94@gmail.com>",
    "maxtremblay <t.maxime@pm.me>",
]
categories = ["science", "mathematics", "algorithms"]
description = "CubeCL Standard Library."
edition.workspace = true
keywords = []
license.workspace = true
name = "cubecl-std"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/crates/cubecl-std"
version.workspace = true

[dependencies]
cubecl-core = { path = "../cubecl-core", version = "0.5.0", default-features = false }
cubecl-runtime = { path = "../cubecl-runtime", version = "0.5.0", default-features = false }
serde = { workspace = true }
