[package]
authors = []
name = "gelu"
publish = false
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
default = []
wgpu = ["cubecl/wgpu"]
cuda = ["cubecl/cuda"]
mlir = ["cubecl/mlir"]

[dependencies]
cubecl = { path = "../../crates/cubecl", version = "0.5.0" }
half = { workspace = true }
